# Generated by Django 4.0.5 on 2022-06-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingrediente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.plato'),
        ),
    ]
