# Generated by Django 4.0.5 on 2022-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='platos', to='api.ingrediente'),
        ),
    ]
