# Generated by Django 4.0.5 on 2022-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingrediente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
