# Generated by Django 4.0.5 on 2022-06-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingrediente_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='url',
        ),
    ]
